processed 13 tasks

task 4 'run'. lines 9-20:
{
  "gas_used": 1208523,
  "status": "Executed"
}

task 6 'run'. lines 25-50:
{
  "gas_used": 474674,
  "status": "Executed"
}

task 8 'run'. lines 54-67:
{
  "gas_used": 168960,
  "status": "Executed"
}

task 10 'run'. lines 71-87:
{
  "gas_used": 277360,
  "status": "Executed"
}

task 11 'run'. lines 90-104:
{
  "gas_used": 109829,
  "status": "Executed"
}

task 12 'run'. lines 106-120:
{
  "gas_used": 28463,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao_features_proposal"
        }
      },
      "abort_code": "262145"
    }
  }
}
