processed 43 tasks

task 5 'run'. lines 12-35:
{
  "gas_used": 1976205,
  "status": "Executed"
}

task 6 'run'. lines 37-53:
{
  "gas_used": 12429,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao_modify_config_proposal"
        }
      },
      "abort_code": "65938"
    }
  }
}

task 7 'run'. lines 56-72:
{
  "gas_used": 997781,
  "status": "Executed"
}

task 8 'run'. lines 75-91:
{
  "gas_used": 997781,
  "status": "Executed"
}

task 9 'run'. lines 94-110:
{
  "gas_used": 890559,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "function": 20,
      "code_offset": 59
    }
  }
}

task 11 'run'. lines 114-143:
{
  "gas_used": 2146204,
  "status": "Executed"
}

task 12 'run'. lines 146-174:
{
  "gas_used": 2259580,
  "status": "Executed"
}

task 13 'run'. lines 177-204:
{
  "gas_used": 1830753,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "198016"
    }
  }
}

task 14 'run'. lines 207-228:
{
  "gas_used": 1682551,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66946"
    }
  }
}

task 15 'run'. lines 231-259:
{
  "gas_used": 946597,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66940"
    }
  }
}

task 16 'run'. lines 262-288:
{
  "gas_used": 158917,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66941"
    }
  }
}

task 17 'run'. lines 291-313:
{
  "gas_used": 94431,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66940"
    }
  }
}

task 18 'run'. lines 316-328:
{
  "gas_used": 78844,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66941"
    }
  }
}

task 19 'run'. lines 331-343:
{
  "gas_used": 80542,
  "status": "Executed"
}

task 20 'run'. lines 346-358:
{
  "gas_used": 15120,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66940"
    }
  }
}

task 21 'run'. lines 361-375:
{
  "gas_used": 76190,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "198011"
    }
  }
}

task 23 'run'. lines 379-399:
{
  "gas_used": 130933,
  "status": "Executed"
}

task 24 'run'. lines 402-416:
{
  "gas_used": 83431,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "394621"
    }
  }
}

task 25 'run'. lines 419-444:
{
  "gas_used": 1066336,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "198011"
    }
  }
}

task 26 'run'. lines 447-461:
{
  "gas_used": 134457,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "198011"
    }
  }
}

task 27 'run'. lines 464-490:
{
  "gas_used": 152978,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "198011"
    }
  }
}

task 28 'run'. lines 493-512:
{
  "gas_used": 209708,
  "status": "Executed"
}

task 30 'run'. lines 517-539:
{
  "gas_used": 358585,
  "status": "Executed"
}

task 32 'run'. lines 543-557:
{
  "gas_used": 152160,
  "status": "Executed"
}

task 33 'run'. lines 560-574:
{
  "gas_used": 132905,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "198011"
    }
  }
}

task 34 'run'. lines 577-591:
{
  "gas_used": 161230,
  "status": "Executed"
}

task 35 'run'. lines 593-606:
{
  "gas_used": 997781,
  "status": "Executed"
}

task 37 'run'. lines 612-638:
{
  "gas_used": 1743857,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66946"
    }
  }
}

task 38 'run'. lines 641-665:
{
  "gas_used": 159081,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66946"
    }
  }
}

task 39 'run'. lines 667-681:
{
  "gas_used": 79008,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66946"
    }
  }
}

task 40 'run'. lines 684-715:
{
  "gas_used": 2259578,
  "status": "Executed"
}

task 42 'run'. lines 720-745:
{
  "gas_used": 144521,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66946"
    }
  }
}
