processed 18 tasks

task 4 'run'. lines 67-82:
{
  "gas_used": 1344594,
  "status": "Executed"
}

task 5 'run'. lines 85-105:
{
  "gas_used": 383048,
  "status": "Executed"
}

task 6 'run'. lines 108-123:
{
  "gas_used": 38039,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66943"
    }
  }
}

task 7 'run'. lines 126-142:
{
  "gas_used": 38039,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66943"
    }
  }
}

task 8 'run'. lines 145-160:
{
  "gas_used": 38144,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66942"
    }
  }
}

task 9 'run'. lines 163-178:
{
  "gas_used": 38039,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66943"
    }
  }
}

task 10 'run'. lines 181-190:
{
  "gas_used": 24344,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao_modify_config_proposal"
        }
      },
      "abort_code": "262545"
    }
  }
}

task 11 'run'. lines 193-232:
{
  "gas_used": 213944,
  "status": "Executed"
}

task 12 'run'. lines 235-261:
{
  "gas_used": 54741,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66942"
    }
  }
}

task 13 'run'. lines 264-284:
{
  "gas_used": 11224,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66943"
    }
  }
}

task 14 'run'. lines 287-307:
{
  "gas_used": 11264,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66943"
    }
  }
}

task 15 'run'. lines 310-329:
{
  "gas_used": 11372,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66943"
    }
  }
}

task 16 'run'. lines 332-352:
{
  "gas_used": 11409,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66943"
    }
  }
}

task 17 'run'. lines 355-375:
{
  "gas_used": 11449,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66943"
    }
  }
}
