processed 13 tasks

task 4 'run'. lines 9-21:
{
  "gas_used": 998936,
  "status": "Executed"
}

task 6 'run'. lines 26-54:
{
  "gas_used": 1897076,
  "status": "Executed"
}

task 8 'run'. lines 58-71:
{
  "gas_used": 168960,
  "status": "Executed"
}

task 10 'run'. lines 75-91:
{
  "gas_used": 277860,
  "status": "Executed"
}

task 11 'run'. lines 94-108:
{
  "gas_used": 110329,
  "status": "Executed"
}

task 12 'run'. lines 110-124:
{
  "gas_used": 28463,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao_features_proposal"
        }
      },
      "abort_code": "262145"
    }
  }
}
