processed 19 tasks

task 5 'run'. lines 97-118:
{
  "gas_used": 2056079,
  "status": "Executed"
}

task 6 'run'. lines 120-142:
{
  "gas_used": 300071,
  "status": "Executed"
}

task 7 'run'. lines 143-156:
{
  "gas_used": 25441,
  "status": "Executed"
}

task 8 'run'. lines 158-177:
{
  "gas_used": 207203,
  "status": "Executed"
}

task 9 'run'. lines 179-191:
{
  "gas_used": 43196,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao_upgrade_module_proposal"
        }
      },
      "abort_code": "262545"
    }
  }
}

task 10 'run'. lines 194-206:
{
  "gas_used": 45335,
  "status": "Executed"
}

task 11 'run'. lines 208-228:
{
  "gas_used": 61569,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66938"
    }
  }
}

task 12 'run'. lines 230-249:
{
  "gas_used": 1915406,
  "status": "Executed"
}

task 14 'run'. lines 254-294:
{
  "gas_used": 2660966,
  "status": "Executed"
}

task 16 'run'. lines 299-314:
{
  "gas_used": 202632,
  "status": "Executed"
}

task 18 'run'. lines 318-334:
{
  "gas_used": 194312,
  "status": "Executed"
}
