processed 19 tasks

task 3 'publish'. lines 7-94:
warning[W09001]: unused alias
   ┌─ TEMPFILE:13:35
   │
13 │     use starcoin_framework::coin::paired_metadata;
   │                                   ^^^^^^^^^^^^^^^ Unused 'use' of alias 'paired_metadata'. Consider removing it



task 5 'run'. lines 98-119:
{
  "gas_used": 2011967,
  "status": "Executed"
}

task 6 'run'. lines 121-143:
{
  "gas_used": 285367,
  "status": "Executed"
}

task 7 'run'. lines 144-157:
{
  "gas_used": 25441,
  "status": "Executed"
}

task 8 'run'. lines 159-178:
{
  "gas_used": 207203,
  "status": "Executed"
}

task 9 'run'. lines 180-192:
{
  "gas_used": 43196,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao_upgrade_module_proposal"
        }
      },
      "abort_code": "262545"
    }
  }
}

task 10 'run'. lines 195-207:
{
  "gas_used": 45335,
  "status": "Executed"
}

task 11 'run'. lines 209-229:
{
  "gas_used": 61569,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66938"
    }
  }
}

task 12 'run'. lines 231-250:
{
  "gas_used": 1915406,
  "status": "Executed"
}

task 14 'run'. lines 255-295:
{
  "gas_used": 2616854,
  "status": "Executed"
}

task 16 'run'. lines 300-315:
{
  "gas_used": 202632,
  "status": "Executed"
}

task 18 'run'. lines 319-335:
{
  "gas_used": 194312,
  "status": "Executed"
}
