version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "02:00"
    # Use UTC +08:00
    timezone: "Asia/Shanghai"
  open-pull-requests-limit: 3
  groups:
    minor-and-patch:
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"
    major-updates:
      patterns:
        - "*"
      update-types:
        - "major"
  # Major updates are grouped to reduce PR volume.
