processed 11 tasks

task 3 'run'. lines 7-14:
{
  "gas_used": 14623,
  "status": {
    "Keep": "Executed"
  }
}

task 4 'run'. lines 16-24:
{
  "gas_used": 16116,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "Timestamp"
          }
        },
        3073
      ]
    }
  }
}

task 5 'run'. lines 26-35:
{
  "gas_used": 21945,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "CoreAddresses"
          }
        },
        2818
      ]
    }
  }
}

task 6 'run'. lines 39-48:
{
  "gas_used": 15687,
  "status": {
    "Keep": {
      "ExecutionFailure": {
        "location": {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "Timestamp"
          }
        },
        "function": 1,
        "code_offset": 7
      }
    }
  }
}

task 7 'run'. lines 52-61:
{
  "gas_used": 21945,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "CoreAddresses"
          }
        },
        2818
      ]
    }
  }
}

task 8 'run'. lines 64-73:
{
  "gas_used": 27291,
  "status": {
    "Keep": "Executed"
  }
}

task 9 'run'. lines 78-87:
{
  "gas_used": 34856,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "Timestamp"
          }
        },
        3591
      ]
    }
  }
}

task 10 'run'. lines 90-101:
{
  "gas_used": 34860,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "Timestamp"
          }
        },
        3591
      ]
    }
  }
}
