[dependencies]
anyhow = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
starcoin-vm-types = { path = "../vm-types" }
move-core-types = { git = "https://github.com/starcoinorg/move", rev = "24eccc3867aaad42d25f1661685ae0fd6546cb83" }

[package]
authors = { workspace = true }
edition = { workspace = true }
name = "starcoin-status-translator"
version = "2.0.1"
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
