[package]
name = "starcoin-package-builder"
description = "Helper for building Move packages for tests"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
starcoin-framework = { path = "../framework" }
itertools = { workspace = true }
move-command-line-common = { git = "https://github.com/starcoinorg/move", rev = "bd872458e2a08f0428aa6f6e17c07da61a49bd62" }
move-package = { git = "https://github.com/starcoinorg/move", rev = "bd872458e2a08f0428aa6f6e17c07da61a49bd62" }
tempfile = { workspace = true }
