processed 12 tasks

task 3 'run'. lines 7-32:
{
  "gas_used": 1345205,
  "status": "Executed"
}

task 4 'run'. lines 35-62:
{
  "gas_used": 723016,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "system_addresses"
        }
      },
      "abort_code": "327683"
    }
  }
}

task 5 'run'. lines 65-89:
{
  "gas_used": 747007,
  "status": "Executed"
}

task 6 'run'. lines 92-116:
{
  "gas_used": 757912,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "block_reward"
        }
      },
      "abort_code": "65638"
    }
  }
}

task 7 'run'. lines 119-149:
{
  "gas_used": 1340969,
  "status": "Executed"
}

task 8 'run'. lines 152-179:
{
  "gas_used": 3060703,
  "status": "Executed"
}

task 9 'run'. lines 182-206:
{
  "gas_used": 1340973,
  "status": "Executed"
}

task 10 'run'. lines 209-234:
{
  "gas_used": 1078053,
  "status": "Executed"
}

task 11 'run'. lines 237-262:
{
  "gas_used": 1340973,
  "status": "Executed"
}
