processed 15 tasks

task 3 'run'. lines 8-20:
{
  "gas_used": 25441,
  "status": "Executed"
}

task 4 'run'. lines 22-41:
{
  "gas_used": 207203,
  "status": "Executed"
}

task 5 'run'. lines 42-53:
{
  "gas_used": 29051,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "stc_transaction_package_validation"
        }
      },
      "abort_code": "65638"
    }
  }
}

task 6 'run'. lines 55-67:
{
  "gas_used": 45976,
  "status": "Executed"
}

task 7 'run'. lines 68-79:
{
  "gas_used": 44488,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "stc_transaction_package_validation"
        }
      },
      "abort_code": "65640"
    }
  }
}

task 9 'run'. lines 83-96:
{
  "gas_used": 45890,
  "status": "Executed"
}

task 10 'run'. lines 97-108:
{
  "gas_used": 31514,
  "status": "Executed"
}

task 11 'run'. lines 109-118:
{
  "gas_used": 26985,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "stc_transaction_package_validation"
        }
      },
      "abort_code": "196710"
    }
  }
}

task 12 'run'. lines 120-134:
{
  "gas_used": 49372,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "stc_transaction_package_validation"
        }
      },
      "abort_code": "65642"
    }
  }
}

task 13 'run'. lines 136-150:
{
  "gas_used": 180019,
  "status": "Executed"
}

task 14 'run'. lines 153-166:
{
  "gas_used": 89781,
  "status": "Executed"
}
