processed 12 tasks

task 3 'run'. lines 8-27:
{
  "gas_used": 1905475,
  "status": "Executed"
}

task 4 'run'. lines 30-70:
{
  "gas_used": 983195,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "system_addresses"
        }
      },
      "abort_code": "327683"
    }
  }
}

task 5 'run'. lines 73-107:
{
  "gas_used": 1059814,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "stc_transaction_validation"
        }
      },
      "abort_code": "65540"
    }
  }
}

task 6 'run'. lines 110-145:
{
  "gas_used": 340105,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "stc_transaction_validation"
        }
      },
      "abort_code": "65537"
    }
  }
}

task 7 'run'. lines 148-187:
{
  "gas_used": 1070080,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "stc_transaction_validation"
        }
      },
      "abort_code": "65539"
    }
  }
}

task 8 'run'. lines 190-245:
{
  "gas_used": 2197192,
  "status": "Executed"
}

task 9 'run'. lines 248-287:
{
  "gas_used": 1021866,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "stc_transaction_validation"
        }
      },
      "abort_code": "65538"
    }
  }
}

task 10 'run'. lines 290-330:
{
  "gas_used": 984195,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "stc_transaction_validation"
        }
      },
      "abort_code": "131082"
    }
  }
}

task 11 'run'. lines 333-374:
{
  "gas_used": 278162,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "system_addresses"
        }
      },
      "abort_code": "327683"
    }
  }
}
