use cc::Build;

fn main() {
    Build::new()
        .include("ext/")
        .include("ext/common")
        .file("ext/CryptonightR_JIT.c")
        .file("ext/CryptonightR_template.S")
        .file("ext/aesb.c")
        .file("ext/blake256.c")
        .file("ext/chacha.c")
        .file("ext/crypto-ops-data.c")
        .file("ext/crypto-ops.c")
        .file("ext/groestl.c")
        .file("ext/hash-extra-blake.c")
        .file("ext/hash-extra-groestl.c")
        .file("ext/hash-extra-jh.c")
        .file("ext/hash-extra-skein.c")
        .file("ext/hash.c")
        .file("ext/random.c")
        .file("ext/jh.c")
        .file("ext/keccak.c")
        .file("ext/oaes_lib.c")
        .file("ext/skein.c")
        .file("ext/slow-hash.c")
        .file("ext/tree-hash.c")
        .flag("-maes")
        .flag("-Ofast")
        .flag("-fexceptions")
        .compile("cryptonight")
}
