[dependencies]
anyhow = { workspace = true }
starcoin-account = { path = "../../account", package = "starcoin-vm2-account" }
starcoin-account-api = { features = ["mock"], path = "../../account/api", package = "starcoin-vm2-account-api" }
starcoin-config = { workspace = true }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", branch = "upgrade-crates" }
#starcoin-rpc-client = { workspace = true }
starcoin-types = { path = "../../types" }

[package]
edition = { workspace = true }
name = "starcoin-vm2-account-provider"
version = "2.0.1"
authors = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
