processed 14 tasks

task 4 'run'. lines 10-21:
{
  "gas_used": 205062,
  "status": "Executed"
}

task 5 'run'. lines 22-31:
{
  "gas_used": 21883,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "OnChainConfigDao"
        }
      },
      "abort_code": "102658"
    }
  }
}

task 6 'run'. lines 32-42:
{
  "gas_used": 156824,
  "status": "Executed"
}

task 8 'run'. lines 47-60:
{
  "gas_used": 146072,
  "status": "Executed"
}

task 11 'run'. lines 67-87:
{
  "gas_used": 153560,
  "status": "Executed"
}

task 13 'run'. lines 92-106:
{
  "gas_used": 111895,
  "status": "Executed"
}
