processed 43 tasks

task 5 'run'. lines 11-27:
{
  "gas_used": 2281544,
  "status": "Executed"
}

task 6 'run'. lines 29-45:
{
  "gas_used": 12429,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao_modify_config_proposal"
        }
      },
      "abort_code": "65938"
    }
  }
}

task 7 'run'. lines 48-64:
{
  "gas_used": 1191224,
  "status": "Executed"
}

task 8 'run'. lines 67-83:
{
  "gas_used": 1191224,
  "status": "Executed"
}

task 9 'run'. lines 86-101:
{
  "gas_used": 1084002,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "function": 18,
      "code_offset": 60
    }
  }
}

task 11 'run'. lines 106-132:
{
  "gas_used": 447050,
  "status": "Executed"
}

task 12 'run'. lines 135-162:
{
  "gas_used": 1256398,
  "status": "Executed"
}

task 13 'run'. lines 165-190:
{
  "gas_used": 1243577,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "198016"
    }
  }
}

task 14 'run'. lines 193-212:
{
  "gas_used": 1148877,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66946"
    }
  }
}

task 15 'run'. lines 215-238:
{
  "gas_used": 1131515,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66940"
    }
  }
}

task 16 'run'. lines 241-269:
{
  "gas_used": 59161,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66941"
    }
  }
}

task 17 'run'. lines 272-296:
{
  "gas_used": 41415,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66940"
    }
  }
}

task 18 'run'. lines 299-313:
{
  "gas_used": 32104,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66941"
    }
  }
}

task 19 'run'. lines 316-330:
{
  "gas_used": 33802,
  "status": "Executed"
}

task 20 'run'. lines 333-347:
{
  "gas_used": 15120,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66940"
    }
  }
}

task 21 'run'. lines 350-366:
{
  "gas_used": 29436,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "198011"
    }
  }
}

task 23 'run'. lines 371-393:
{
  "gas_used": 37453,
  "status": "Executed"
}

task 24 'run'. lines 396-412:
{
  "gas_used": 36677,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "394621"
    }
  }
}

task 25 'run'. lines 415-437:
{
  "gas_used": 1157366,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "198011"
    }
  }
}

task 26 'run'. lines 440-455:
{
  "gas_used": 40977,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "198011"
    }
  }
}

task 27 'run'. lines 458-476:
{
  "gas_used": 53194,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "198011"
    }
  }
}

task 28 'run'. lines 479-497:
{
  "gas_used": 69488,
  "status": "Executed"
}

task 30 'run'. lines 502-524:
{
  "gas_used": 265105,
  "status": "Executed"
}

task 32 'run'. lines 528-542:
{
  "gas_used": 69700,
  "status": "Executed"
}

task 33 'run'. lines 545-560:
{
  "gas_used": 39425,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "198011"
    }
  }
}

task 34 'run'. lines 563-577:
{
  "gas_used": 67750,
  "status": "Executed"
}

task 35 'run'. lines 580-593:
{
  "gas_used": 1191224,
  "status": "Executed"
}

task 37 'run'. lines 598-620:
{
  "gas_used": 1162955,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66946"
    }
  }
}

task 38 'run'. lines 623-642:
{
  "gas_used": 59297,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66946"
    }
  }
}

task 39 'run'. lines 645-660:
{
  "gas_used": 32254,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66946"
    }
  }
}

task 40 'run'. lines 663-685:
{
  "gas_used": 1256396,
  "status": "Executed"
}

task 42 'run'. lines 690-713:
{
  "gas_used": 51027,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "dao"
        }
      },
      "abort_code": "66946"
    }
  }
}
