[dependencies]
anyhow = { workspace = true }
hex = { workspace = true }
move-binary-format = { git = "https://github.com/starcoinorg/move", rev = "7d37ed75c76f34abd2ea71774dcf784408625887" }
move-core-types = { git = "https://github.com/starcoinorg/move", rev = "7d37ed75c76f34abd2ea71774dcf784408625887" }
serde = { features = ["derive", "rc"], workspace = true }
serde_json = { workspace = true }
starcoin-vm-types = { path = "../vm-types" }

[package]
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
name = "starcoin-vm2-resource-viewer"
publish = { workspace = true }
version = "2.0.1"
homepage = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
