processed 43 tasks

task 5 'run'. lines 12-29:
{
  "gas_used": 296684,
  "status": "Executed"
}

task 6 'run'. lines 31-41:
{
  "gas_used": 12417,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "ModifyDaoConfigProposal"
        }
      },
      "abort_code": "102919"
    }
  }
}

task 7 'run'. lines 44-54:
{
  "gas_used": 157138,
  "status": "Executed"
}

task 8 'run'. lines 58-68:
{
  "gas_used": 157138,
  "status": "Executed"
}

task 9 'run'. lines 71-81:
{
  "gas_used": 120357,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "function": 18,
      "code_offset": 45
    }
  }
}

task 11 'run'. lines 86-104:
{
  "gas_used": 146714,
  "status": "Executed"
}

task 12 'run'. lines 107-127:
{
  "gas_used": 160129,
  "status": "Executed"
}

task 13 'run'. lines 131-155:
{
  "gas_used": 147306,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "360449"
    }
  }
}

task 14 'run'. lines 158-176:
{
  "gas_used": 92092,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "360967"
    }
  }
}

task 15 'run'. lines 179-197:
{
  "gas_used": 74751,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "359431"
    }
  }
}

task 16 'run'. lines 200-218:
{
  "gas_used": 59105,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "359687"
    }
  }
}

task 17 'run'. lines 221-239:
{
  "gas_used": 41380,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "359431"
    }
  }
}

task 18 'run'. lines 242-255:
{
  "gas_used": 32071,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "359687"
    }
  }
}

task 19 'run'. lines 258-271:
{
  "gas_used": 33781,
  "status": "Executed"
}

task 20 'run'. lines 274-287:
{
  "gas_used": 15108,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "359431"
    }
  }
}

task 21 'run'. lines 290-304:
{
  "gas_used": 29403,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "359169"
    }
  }
}

task 23 'run'. lines 309-324:
{
  "gas_used": 37409,
  "status": "Executed"
}

task 24 'run'. lines 327-341:
{
  "gas_used": 36643,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "359682"
    }
  }
}

task 25 'run'. lines 344-364:
{
  "gas_used": 100558,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "359169"
    }
  }
}

task 26 'run'. lines 367-381:
{
  "gas_used": 40921,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "359169"
    }
  }
}

task 27 'run'. lines 384-402:
{
  "gas_used": 53136,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "359169"
    }
  }
}

task 28 'run'. lines 406-424:
{
  "gas_used": 69401,
  "status": "Executed"
}

task 30 'run'. lines 430-452:
{
  "gas_used": 155460,
  "status": "Executed"
}

task 32 'run'. lines 456-470:
{
  "gas_used": 69654,
  "status": "Executed"
}

task 33 'run'. lines 473-488:
{
  "gas_used": 39369,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "359169"
    }
  }
}

task 34 'run'. lines 491-505:
{
  "gas_used": 67706,
  "status": "Executed"
}

task 35 'run'. lines 508-519:
{
  "gas_used": 157138,
  "status": "Executed"
}

task 37 'run'. lines 525-545:
{
  "gas_used": 106149,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "360967"
    }
  }
}

task 38 'run'. lines 548-566:
{
  "gas_used": 59241,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "360967"
    }
  }
}

task 39 'run'. lines 570-583:
{
  "gas_used": 32221,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "360967"
    }
  }
}

task 40 'run'. lines 586-606:
{
  "gas_used": 160127,
  "status": "Executed"
}

task 42 'run'. lines 612-630:
{
  "gas_used": 50973,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "360967"
    }
  }
}
