// Copyright (c) The Starcoin Core Contributors
// SPDX-License-Identifier: Apache-2.0

pub type ByteCode = Vec<u8>;

mod account_state_set_view;
mod accumulator_info_view;
mod accumulator_proof_view;
mod annotated_move_struct_view;
mod annotated_move_value_view;
mod arguments_view;
mod block_header_view;
mod block_info_view;
mod block_metadata_view;
mod block_transaction_view;
mod block_view;
mod byte_code_or_script_function;
mod bytes_view;
mod chain_info_view;
mod code_view;
mod decoded_script_view;
mod dry_run_output_view;
mod event_with_proof_view;
mod function_arg_type_view;
mod minted_block_view;
mod peer_info_view;
mod raw_block_view;
mod raw_user_transaction_view;
mod resource_view;
mod scripts_data;
mod signed_user_transaction_view;
mod spare_merkle_proof_view;
mod state_key_view;
mod state_with_proof_view;
mod state_with_table_item_proof_view;
mod str_view;
mod table_info_view;
mod table_item_view;
mod transaction_event_response;
mod transaction_event_view;
mod transaction_info_view;
mod transaction_output_action;
mod transaction_output_table_item_action;
mod transaction_output_view;
mod transaction_payload_view;
mod transaction_request;
mod transaction_status_view;
mod transaction_view;
mod transaction_with_proof;
mod vm_status_explain_view;
mod write_op_value_view;
mod write_op_view;
