[package]
name = "starcoin-vm2-rpc-api"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
jsonrpsee = { workspace = true, features = ["server", "async-client", "macros"] }
serde = { features = ["derive"], workspace = true }
schemars = { workspace = true }

starcoin-accumulator = { workspace = true }
starcoin-vm1-types = { path = "../../../types" }
starcoin-vm2-types = { workspace = true }
starcoin-vm2-vm-types = { workspace = true }
starcoin-vm2-abi-decoder = { workspace = true }
starcoin-vm2-abi-types = { workspace = true }
starcoin-vm2-account-api = { workspace = true }
starcoin-vm2-crypto = { workspace = true }
