processed 16 tasks

task 9 'run'. lines 386-395:
{
  "gas_used": 32583,
  "status": "Executed"
}

task 10 'run'. lines 397-410:
{
  "gas_used": 121542,
  "status": "Executed"
}

task 11 'run'. lines 412-420:
{
  "gas_used": 27121,
  "status": "Executed"
}

task 12 'run'. lines 422-431:
{
  "gas_used": 36706,
  "status": "Executed"
}

task 13 'run'. lines 433-445:
{
  "gas_used": 24191,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0xc65e3b77aaa8ab9d5810bcf0b41d1a31",
          "name": "NonFungibleToken"
        }
      },
      "abort_code": "8004"
    }
  }
}

task 14 'run'. lines 447-455:
{
  "gas_used": 46960,
  "status": "Executed"
}

task 15 'run'. lines 457-469:
{
  "gas_used": 63320,
  "status": "Executed"
}
