processed 19 tasks

task 5 'run'. lines 32-52:
{
  "gas_used": 125500,
  "status": {
    "Keep": "Executed"
  }
}

task 6 'run'. lines 54-68:
{
  "gas_used": 113677,
  "status": {
    "Keep": "Executed"
  }
}

task 7 'run'. lines 71-82:
{
  "gas_used": 34360,
  "status": {
    "Keep": "Executed"
  }
}

task 8 'run'. lines 85-98:
{
  "gas_used": 116661,
  "status": {
    "Keep": "Executed"
  }
}

task 9 'run'. lines 101-110:
{
  "gas_used": 25986,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "Dao"
          }
        },
        358658
      ]
    }
  }
}

task 10 'run'. lines 113-124:
{
  "gas_used": 21364,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "MintDaoProposal"
          }
        },
        102658
      ]
    }
  }
}

task 11 'run'. lines 127-137:
{
  "gas_used": 163397,
  "status": {
    "Keep": "Executed"
  }
}

task 12 'run'. lines 140-150:
{
  "gas_used": 150826,
  "status": {
    "Keep": "Executed"
  }
}

task 14 'run'. lines 156-172:
{
  "gas_used": 141603,
  "status": {
    "Keep": "Executed"
  }
}

task 16 'run'. lines 177-198:
{
  "gas_used": 154474,
  "status": {
    "Keep": "Executed"
  }
}

task 18 'run'. lines 204-222:
{
  "gas_used": 158162,
  "status": {
    "Keep": "Executed"
  }
}
