processed 12 tasks

task 3 'run'. lines 8-23:
{
  "gas_used": 318252,
  "status": "Executed"
}

task 4 'run'. lines 27-59:
{
  "gas_used": 91881,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "CoreAddresses"
        }
      },
      "abort_code": "2818"
    }
  }
}

task 5 'run'. lines 63-90:
{
  "gas_used": 168011,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Account"
        }
      },
      "abort_code": "1031"
    }
  }
}

task 6 'run'. lines 94-122:
{
  "gas_used": 140032,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Account"
        }
      },
      "abort_code": "263"
    }
  }
}

task 7 'run'. lines 126-156:
{
  "gas_used": 174473,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Account"
        }
      },
      "abort_code": "775"
    }
  }
}

task 8 'run'. lines 160-205:
{
  "gas_used": 239024,
  "status": "Executed"
}

task 9 'run'. lines 209-239:
{
  "gas_used": 174341,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Account"
        }
      },
      "abort_code": "519"
    }
  }
}

task 10 'run'. lines 243-274:
{
  "gas_used": 95560,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Account"
        }
      },
      "abort_code": "2568"
    }
  }
}

task 11 'run'. lines 278-309:
{
  "gas_used": 89451,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "CoreAddresses"
        }
      },
      "abort_code": "2818"
    }
  }
}
