[dependencies]
anyhow = { workspace = true }
move-model = { git = "https://github.com/starcoinorg/move", rev = "ed9d919d05fedeae9cf433d4f44f6aba526580c3" }
starcoin-vm2-abi-types = { workspace = true }
starcoin-vm2-resource-viewer = { workspace = true }
starcoin-vm2-vm-types = { workspace = true }
sha3 = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }
starcoin-cached-packages = { path = "../../framework/cached-packages" }
test-helper = { path = "../../../vm2/test-helper", package = "starcoin-test-helper" }

[package]
authors = { workspace = true }
edition = { workspace = true }
name = "starcoin-vm2-abi-resolver"
version = "2.0.1"
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[features]
default = []
ai-metadata = ["starcoin-vm2-abi-types/ai-metadata", "sha3"]
