processed 13 tasks

task 5 'run'. lines 29-42:
{
  "gas_used": 83553,
  "status": "Executed"
}

task 6 'run'. lines 45-61:
{
  "gas_used": 72894,
  "status": "Executed"
}

task 7 'run'. lines 64-81:
{
  "gas_used": 88429,
  "status": "Executed"
}

task 8 'run'. lines 84-107:
{
  "gas_used": 82561,
  "status": "Executed"
}

task 9 'run'. lines 110-124:
{
  "gas_used": 66029,
  "status": "Executed"
}

task 10 'run'. lines 127-142:
{
  "gas_used": 35628,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Collection2"
        }
      },
      "abort_code": "26626"
    }
  }
}

task 11 'run'. lines 146-170:
{
  "gas_used": 133526,
  "status": "Executed"
}

task 12 'run'. lines 173-188:
{
  "gas_used": 21613,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Collection2"
        }
      },
      "abort_code": "25857"
    }
  }
}
