processed 11 tasks

task 4 'run'. lines 25-40:
{
  "gas_used": 130699,
  "status": "Executed"
}

task 5 'run'. lines 42-55:
{
  "gas_used": 113077,
  "status": "Executed"
}

task 6 'run'. lines 57-65:
{
  "gas_used": 20271,
  "status": "Executed"
}

task 7 'run'. lines 67-82:
{
  "gas_used": 68287,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Token"
        }
      },
      "abort_code": "26120"
    }
  }
}

task 8 'run'. lines 84-96:
{
  "gas_used": 86133,
  "status": "Executed"
}

task 9 'run'. lines 98-109:
{
  "gas_used": 81241,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Token"
        }
      },
      "abort_code": "4097"
    }
  }
}

task 10 'run'. lines 111-121:
{
  "gas_used": 29855,
  "status": "Executed"
}
