processed 19 tasks

task 5 'run'. lines 32-52:
{
  "gas_used": 125010,
  "status": "Executed"
}

task 6 'run'. lines 54-68:
{
  "gas_used": 113077,
  "status": "Executed"
}

task 7 'run'. lines 71-82:
{
  "gas_used": 34112,
  "status": "Executed"
}

task 8 'run'. lines 85-98:
{
  "gas_used": 114416,
  "status": "Executed"
}

task 9 'run'. lines 101-110:
{
  "gas_used": 25922,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Dao"
        }
      },
      "abort_code": "358658"
    }
  }
}

task 10 'run'. lines 113-124:
{
  "gas_used": 21300,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "MintDaoProposal"
        }
      },
      "abort_code": "102658"
    }
  }
}

task 11 'run'. lines 127-137:
{
  "gas_used": 159206,
  "status": "Executed"
}

task 12 'run'. lines 140-150:
{
  "gas_used": 145729,
  "status": "Executed"
}

task 14 'run'. lines 156-172:
{
  "gas_used": 139354,
  "status": "Executed"
}

task 16 'run'. lines 177-198:
{
  "gas_used": 154048,
  "status": "Executed"
}

task 18 'run'. lines 204-222:
{
  "gas_used": 150480,
  "status": "Executed"
}
