processed 12 tasks

task 3 'run'. lines 7-21:
{
  "gas_used": 189363,
  "status": "Executed"
}

task 4 'run'. lines 24-40:
{
  "gas_used": 29041,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "CoreAddresses"
        }
      },
      "abort_code": "2818"
    }
  }
}

task 5 'run'. lines 43-58:
{
  "gas_used": 33791,
  "status": "Executed"
}

task 6 'run'. lines 61-76:
{
  "gas_used": 33282,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "BlockReward"
        }
      },
      "abort_code": "26119"
    }
  }
}

task 7 'run'. lines 80-96:
{
  "gas_used": 417706,
  "status": "Executed"
}

task 8 'run'. lines 99-115:
{
  "gas_used": 372367,
  "status": "Executed"
}

task 9 'run'. lines 118-133:
{
  "gas_used": 196563,
  "status": "Executed"
}

task 10 'run'. lines 136-150:
{
  "gas_used": 86207,
  "status": "Executed"
}

task 11 'run'. lines 153-167:
{
  "gas_used": 196563,
  "status": "Executed"
}
