[package]
name = "starcoin-rpc-tcp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Raw TCP support for Starcoin JSON-RPC"

[dependencies]
futures.workspace = true
futures-util.workspace = true
jsonrpsee = { workspace = true, features = ["server"] }
pin-project.workspace = true
serde_json.workspace = true
starcoin-rpc-ipc = { workspace = true }
tokio = { workspace = true, features = ["net", "rt-multi-thread", "sync", "io-util"] }
tokio-stream.workspace = true
tokio-util = { workspace = true, features = ["codec"] }
tower.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
