processed 11 tasks

task 2 'run'. lines 17-81:
{
  "gas_used": 47766,
  "status": "Executed"
}

task 3 'run'. lines 83-95:
{
  "gas_used": 38048,
  "status": "Executed"
}

task 4 'run'. lines 97-127:
{
  "gas_used": 24809,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "consensus_config"
        }
      },
      "abort_code": "65554"
    }
  }
}

task 5 'run'. lines 129-159:
{
  "gas_used": 24876,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "consensus_config"
        }
      },
      "abort_code": "65554"
    }
  }
}

task 6 'run'. lines 161-191:
{
  "gas_used": 24876,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "consensus_config"
        }
      },
      "abort_code": "65554"
    }
  }
}

task 7 'run'. lines 193-224:
{
  "gas_used": 24876,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "consensus_config"
        }
      },
      "abort_code": "65554"
    }
  }
}

task 8 'run'. lines 226-257:
{
  "gas_used": 24876,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "consensus_config"
        }
      },
      "abort_code": "65554"
    }
  }
}

task 9 'run'. lines 259-290:
{
  "gas_used": 24876,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "consensus_config"
        }
      },
      "abort_code": "65554"
    }
  }
}

task 10 'run'. lines 292-323:
{
  "gas_used": 24876,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "consensus_config"
        }
      },
      "abort_code": "65554"
    }
  }
}
