processed 14 tasks

task 4 'run'. lines 9-21:
{
  "gas_used": 2295051,
  "status": "Executed"
}

task 5 'run'. lines 23-34:
{
  "gas_used": 24987,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "on_chain_config_dao"
        }
      },
      "abort_code": "393617"
    }
  }
}

task 6 'run'. lines 36-51:
{
  "gas_used": 1922496,
  "status": "Executed"
}

task 8 'run'. lines 56-80:
{
  "gas_used": 3133013,
  "status": "Executed"
}

task 11 'run'. lines 87-123:
{
  "gas_used": 549158,
  "status": "Executed"
}

task 13 'run'. lines 128-146:
{
  "gas_used": 241830,
  "status": "Executed"
}
