[dependencies]
jsonrpsee = { workspace = true, features = ["server"] }
serde_json = { workspace = true }
starcoin-config = { workspace = true }
starcoin-logger = { workspace = true }
starcoin-rpc-api = { workspace = true }
starcoin-metrics = { workspace = true }

[package]
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
name = "starcoin-rpc-middleware"
publish = { workspace = true }
version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
