processed 12 tasks

task 4 'run'. lines 67-74:
{
  "gas_used": 63255,
  "status": "Executed"
}

task 5 'run'. lines 77-84:
{
  "gas_used": 87827,
  "status": "Executed"
}

task 6 'run'. lines 86-96:
{
  "gas_used": 61796,
  "status": "Executed"
}

task 7 'run'. lines 99-106:
{
  "gas_used": 34478,
  "status": "Executed"
}

task 8 'run'. lines 108-118:
{
  "gas_used": 24120,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Config"
        }
      },
      "abort_code": "25860"
    }
  }
}

task 9 'run'. lines 120-129:
{
  "gas_used": 45757,
  "status": "Executed"
}

task 10 'run'. lines 132-139:
{
  "gas_used": 58925,
  "status": "Executed"
}

task 11 'run'. lines 142-152:
{
  "gas_used": 61796,
  "status": "Executed"
}
