processed 11 tasks

task 2 'run'. lines 5-41:
{
  "gas_used": 67113,
  "status": "Executed"
}

task 3 'run'. lines 43-54:
{
  "gas_used": 30377,
  "status": "Executed"
}

task 4 'run'. lines 56-87:
{
  "gas_used": 21324,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "ConsensusConfig"
        }
      },
      "abort_code": "4615"
    }
  }
}

task 5 'run'. lines 89-120:
{
  "gas_used": 21404,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "ConsensusConfig"
        }
      },
      "abort_code": "4615"
    }
  }
}

task 6 'run'. lines 122-153:
{
  "gas_used": 21364,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "ConsensusConfig"
        }
      },
      "abort_code": "4615"
    }
  }
}

task 7 'run'. lines 155-187:
{
  "gas_used": 21444,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "ConsensusConfig"
        }
      },
      "abort_code": "4615"
    }
  }
}

task 8 'run'. lines 189-221:
{
  "gas_used": 21484,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "ConsensusConfig"
        }
      },
      "abort_code": "4615"
    }
  }
}

task 9 'run'. lines 223-255:
{
  "gas_used": 21524,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "ConsensusConfig"
        }
      },
      "abort_code": "4615"
    }
  }
}

task 10 'run'. lines 257-289:
{
  "gas_used": 21594,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "ConsensusConfig"
        }
      },
      "abort_code": "4615"
    }
  }
}
