name: Build and Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: build and test
    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: setup environment
        run: |
          bash ./scripts/dev_setup.sh -b -t -y -m
          echo "${CARGO_HOME:-$HOME/.cargo}/bin" >> "$GITHUB_PATH"
      - name: run fmt check
        run: cargo fmt -- --check
      - name: run cargo clean
        run: cargo clean
      - name: run cargo check
        env:
          RUSTFLAGS: -D warnings
        run: cargo clippy --all-targets
      - name: build
        run: cargo build --all
      - name: test
        run: ./scripts/nextest.sh
#       - name: check changed files
#         run: bash ./scripts/changed_files.sh
      - name: Doc Tests
        run: cargo test --doc
      - name: integration test dev environment
        env:
          RUST_LOG: info
          RUST_BACKTRACE: full
          STARCOIN_WS: ${{ secrets.STARCOIN_WS }}
        run: cargo test --test integration -- -e cmd
