name: PR Build and Test
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - dual-verse-dag

jobs:
  build-and-test:
    uses: ./.github/workflows/core-build-test.yml
    with:
      runner: self-hosted
    secrets: inherit